In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nslkdd/KDDTest+.arff
/kaggle/input/nslkdd/KDDTest-21.arff
/kaggle/input/nslkdd/KDDTest1.jpg
/kaggle/input/nslkdd/KDDTrain+.txt
/kaggle/input/nslkdd/KDDTrain+_20Percent.txt
/kaggle/input/nslkdd/KDDTest-21.txt
/kaggle/input/nslkdd/KDDTest+.txt
/kaggle/input/nslkdd/KDDTrain+.arff
/kaggle/input/nslkdd/index.html
/kaggle/input/nslkdd/KDDTrain+_20Percent.arff
/kaggle/input/nslkdd/KDDTrain1.jpg
/kaggle/input/nslkdd/nsl-kdd/KDDTest+.arff
/kaggle/input/nslkdd/nsl-kdd/KDDTest-21.arff
/kaggle/input/nslkdd/nsl-kdd/KDDTest1.jpg
/kaggle/input/nslkdd/nsl-kdd/KDDTrain+.txt
/kaggle/input/nslkdd/nsl-kdd/KDDTrain+_20Percent.txt
/kaggle/input/nslkdd/nsl-kdd/KDDTest-21.txt
/kaggle/input/nslkdd/nsl-kdd/KDDTest+.txt
/kaggle/input/nslkdd/nsl-kdd/KDDTrain+.arff
/kaggle/input/nslkdd/nsl-kdd/index.html
/kaggle/input/nslkdd/nsl-kdd/KDDTrain+_20Percent.arff
/kaggle/input/nslkdd/nsl-kdd/KDDTrain1.jpg


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
columns = [
    'duration', 'protocol_type', 'service', 'flag',
    'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
    'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted',
    'num_root', 'num_file_creations', 'num_shells',
    'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count',
    'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate',
    'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate',
    'label', 'difficulty'
]
df=pd.read_csv("/kaggle/input/nslkdd/KDDTrain+.txt",names=columns)
#list(df.columns)
#df['label'].value_counts()
df['binary_label']=df['label'].apply(lambda x: 0 if x=='normal' else 1)
#df['binary_label'].value_counts()
df=df.drop(['label','difficulty'], axis=1)
#df.dtypes
df=pd.get_dummies(df,columns=['protocol_type','service','flag'])
#df.shape
X=df.drop('binary_label',axis=1)
Y=df['binary_label']
X_train, X_test, Y_train, Y_test= train_test_split(
    X,Y,
    test_size=0.2,
    stratify=Y,
    random_state=42
)
#Y_train.value_counts(normalize=True)
#Y_test.value_counts(normalize=True)
model=LogisticRegression(max_iter=1000, n_jobs=-1)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
cm=confusion_matrix(Y_test, Y_pred)
print(cm)
print(classification_report(Y_test, Y_pred))

[[12900   569]
 [  640 11086]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.96     13469
           1       0.95      0.95      0.95     11726

    accuracy                           0.95     25195
   macro avg       0.95      0.95      0.95     25195
weighted avg       0.95      0.95      0.95     25195



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import GradientBoostingClassifier
columns = [
    'duration', 'protocol_type', 'service', 'flag',
    'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
    'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted',
    'num_root', 'num_file_creations', 'num_shells',
    'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count',
    'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate',
    'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate',
    'label', 'difficulty'
]
#df=pd.read_csv("/kaggle/input/nslkdd/KDDTrain+.txt",names=columns)
df=pd.read_csv("/kaggle/input/nslkdd/KDDTest+.txt", names=columns)
#list(df.columns)
#df['label'].value_counts()
df['binary_label']=df['label'].apply(lambda x: 0 if x=='normal' else 1)
#df['binary_label'].value_counts()
df=df.drop(['label','difficulty'], axis=1)
#df.dtypes
df=pd.get_dummies(df,columns=['protocol_type','service','flag'])
#df.shape
X=df.drop('binary_label',axis=1)
Y=df['binary_label']
X_train, X_test, Y_train, Y_test= train_test_split(
    X,Y,
    test_size=0.2,
    stratify=Y,
    random_state=42
)
#Y_train.value_counts(normalize=True)
#Y_test.value_counts(normalize=True)
#model=LogisticRegression(max_iter=1000, n_jobs=-1)
#model.fit(X_train,Y_train)
#Y_pred=model.predict(X_test)
#cm=confusion_matrix(Y_test, Y_pred)
#print(cm)
#print(classification_report(Y_test, Y_pred))
gb_model=GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, Y_train)
Y_pred_gb=gb_model.predict(X_test)
print(confusion_matrix(Y_test, Y_pred_gb))
print(classification_report(Y_test, Y_pred_gb))

[[1896   46]
 [  40 2527]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1942
           1       0.98      0.98      0.98      2567

    accuracy                           0.98      4509
   macro avg       0.98      0.98      0.98      4509
weighted avg       0.98      0.98      0.98      4509



In [4]:
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import GradientBoostingClassifier
columns = [
    'duration', 'protocol_type', 'service', 'flag',
    'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
    'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted',
    'num_root', 'num_file_creations', 'num_shells',
    'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count',
    'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate',
    'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate',
    'label', 'difficulty'
]
tdf=pd.read_csv("/kaggle/input/nslkdd/KDDTest+.txt", names=columns)
#list(df.columns)
#df['label'].value_counts()
tdf['binary_label']=tdf['label'].apply(lambda x: 0 if x=='normal' else 1)
#df['binary_label'].value_counts()
tdf=tdf.drop(['label','difficulty'], axis=1)
#df.dtypes
tdf=pd.get_dummies(tdf,columns=['protocol_type','service','flag'])
X_test_real=tdf.drop('binary_label',axis=1)
Y_test_real=tdf['binary_label']
X_train, X_test, Y_train, Y_test= train_test_split(
    X_test_real,Y_test_real,
    test_size=0.2,
    stratify=Y_test_real,
    random_state=42
)
X_test_real=X_test_real.reindex(columns=X_train.columns,fill_value=0)
print(X_train.shape)
print(X_test_real.shape)
#Y_train.value_counts(normalize=True)
#Y_test.value_counts(normalize=True)
#model=LogisticRegression(max_iter=1000, n_jobs=-1)
#model.fit(X_train,Y_train)
#Y_pred=model.predict(X_test)
#cm=confusion_matrix(Y_test, Y_pred)
#print(cm)
#print(classification_report(Y_test, Y_pred))
gb_model=GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, Y_train)
Y_pred_real=gb_model.predict(X_test_real)
print(confusion_matrix(Y_test_real, Y_pred_real))
print(classification_report(Y_test_real, Y_pred_real))
#joblib.dump(gb_model, "ids_gb_model.pkl")
#X_train.columns.tolist()

(18035, 116)
(22544, 116)
[[ 9482   229]
 [  181 12652]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      9711
           1       0.98      0.99      0.98     12833

    accuracy                           0.98     22544
   macro avg       0.98      0.98      0.98     22544
weighted avg       0.98      0.98      0.98     22544

